---
baseURL: "https://hacktoberfest.scot"
#disableLanguages = ['fr']
title: "Hacktoberfest Scotland"
disqusShortname: ""
paginate: "6"
summaryLength: "15"

theme:
  - "meghna-hugo"

Params:
  author: "Hacktoberfest Scotland"
  description: "Hacktoberfest Scotland 2020"
  copyright: "Copyright &copy; 2020 [Paul Broadwith](https://blog.pauby.com). Theme Copyright &copy; 2020 Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"
  google_analytics_id: ""
  logo: "images/hacktoberfest-scotland-logo.png"
  post_share: false

  cookies:
    enable: false
    expire_days: 2

  map:
    enable: false
    gmap_api: ""
    map_latitude: ""
    map_longitude: ""
    map_marker: ""

  plugins:
    css:
      - link: "plugins/bootstrap/bootstrap.min.css"
      - link: "plugins/themify-icons/themify-icons.css"
      - link: "plugins/magnific-popup/magnific-popup.css"
      - link: "plugins/slick/slick.css"
      - link: "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
      - link: "https://fonts.googleapis.com/css2?family=Fira+Sans&family=Roboto&display=swap"
#      - link: "assets/css/custom.css"
    js:
      - link: "plugins/jquery/jquery.min.js"
      - link: "plugins/bootstrap/bootstrap.min.js"
      - link: "plugins/slick/slick.min.js"
      - link: "plugins/shuffle/shuffle.min.js"
      - link: "plugins/magnific-popup/jquery.magnific-popup.min.js"
      - link: "plugins/lazy-load/lozad.min.js"
      - link: "plugins/google-map/map.js"

  preloader:
    enable: false
    preloader: "images/hacktoberfest-scotland-logo.png"

menu:
  main:
    - name: "speakers"
      pre: "#"
      url: "speakers"
      weight: "1"
    - name: "agenda"
      pre: "#"
      url: "agenda"
      weight: "2"
    - name: "rooms"
      pre: "#"
      url: "channels"
      weight: "3"
    - name: "organisers"
      pre: "#"
      url: "organisers"
      weight: "4"
